version: '3'

services: 
    api_catalog:
        build: 
            context: .
            dockerfile: ./docker/python/python.dockerfile 
        expose: 
        - "5000"
        ports: 
        - "5000:5000"
        volumes: 
        - ./api_catalog:/src
        networks:
        - mongo-network
        depends_on: 
        - mongodb

    api_recomendations:
        build: 
            context: .
            dockerfile: ./docker/node/node.dockerfile 
        expose: 
        - "3000"
        ports: 
        - "3000:3000"
        volumes: 
        - ./api_recomendations:/app

    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"
        networks:
        - mongo-network

    mongo-seed:
        build: 
            context: .
            dockerfile: ./docker/mongo/mongoseed.dockerfile
        links:
        - mongodb
        depends_on: 
        - mongodb
        networks:
        - mongo-network

networks: 
    mongo-network:
      driver: bridge