version: '3'

services: 
    front:
        build: 
            context: .
            dockerfile: ./docker/nginx/nginx.dockerfile
        ports: 
        - "8001:80"
        networks:
        - backend

    api_catalog:
        build: 
            context: .
            dockerfile: ./docker/python/python.dockerfile 
        expose: 
        - "5000"
        ports: 
        - "${API_CATALOG_PORT}:5000"
        volumes: 
        - ./api_catalog:/src
        networks:
        - mongo-network
        - backend
        depends_on: 
        - mongodb

    api_recomendations:
        build: 
            context: .
            dockerfile: ./docker/node/node.dockerfile 
        expose: 
        - "3000"
        ports: 
        - "${API_RECOMENDATIONS_PORT}:3000"
        volumes: 
        - ./api_recomendations:/app
        networks: 
        - backend
        environment:
        - PORT=3000
        - REDIS_URL=redis://cache
        - API_CATALOG_URL=api_catalog:5000

    redis:
        image: redis
        container_name: cache
        networks: 
        - backend
        expose:
        - 6379

    mongodb:
        container_name: mongodb
        image: mongo
        ports:
        - "${MONGODB_PORT}:27017"
        networks:
        - mongo-network

    mongo-seed:
        build: 
            context: .
            dockerfile: ./docker/mongo/mongoseed.dockerfile
        links:
        - mongodb
        depends_on: 
        - mongodb
        networks:
        - mongo-network

networks: 
    mongo-network:
      driver: bridge
    backend:
      driver: bridge